export type Department = {
  accountNo: number;
  ancestorsCodes: string[];
  childrenNo: number;
  code: string;
  createdBy: string | null;
  createdByCustomer: boolean;
  createdDate: string | null;
  description: string | null;
  descriptionTranslations: Record<string, any>;
  employeeNo: number;
  id: string | null;
  lastModifiedBy: string | null;
  lastModifiedByCustomer: boolean;
  lastModifiedDate: string | null;
  level: number;
  modes: string[];
  name: string | null;
  nameTranslations: Record<string, any>;
  orderNo: number;
  parent: string | null;
  parentCode: string | null;
  system: boolean;
  timekeeper: string | null;
  titleCodes: string[];
  titleNo: number;
};

type Title = {
  accountNo: number;
  code: string;
  createdBy: string | null;
  createdDate: string | null;
  departmentCodes: string[] | null;
  departmentNo: number;
  departmentTypeCodes: string[] | null;
  description: string | null;
  descriptionTranslations: Record<string, any> | null;
  employeeNo: number;
  lastModifiedBy: string | null;
  lastModifiedDate: string | null;
  name: string | null;
  nameTranslations: Record<string, any> | null;
  orderNo: number;
  system: boolean;
};

export type Result = {
  address: string | null;
  addressText: string | null;
  allowLoginCMS: boolean;
  ancestorsDepartmentCode: string[];
  authorizes: string | null;
  avatar: string | null;
  bankUser: string | null;
  basicSalary: number | null;
  birthDay: string | null;
  cccd: string | null;
  changePassword: boolean;
  checkinCode: string | null;
  createdBy: string;
  createdByCms: boolean;
  createdDate: string;
  dateLeave: string | null;
  degrees: string | null;
  department: Department;
  departmentCode: string;
  departmentModes: string[];
  departmentRole: string;
  dependentPersons: string | null;
  email: string;
  employeeNormal: boolean;
  employeeWorkShift: boolean;
  enabled: boolean;
  faceEmbeddings: Record<string, any>[];
  firstName: string | null;
  fullName: string;
  gender: string | null;
  historyChangeDepartmentAndTitles: string[];
  historyChangeSalaries: string[];
  historyLaborContracts: string | null;
  imageCCCD: string | null;
  issueDateCCCD: string | null;
  issuePlaceCCCD: string | null;
  laborContract: string | null;
  lastModifiedBy: string;
  lastModifiedDate: string;
  lastName: string | null;
  leaveEmployeeInfo: string | null;
  link: string | null;
  listRole: string | null;
  maritalStatus: boolean;
  middleName: string | null;
  national: string | null;
  otherName: string | null;
  phone: string | null;
  placeBirth: string | null;
  roles: string[];
  salary: number | null;
  salaryInHour: number | null;
  salaryWorkShift: number | null;
  scopeDepartmentAndTitles: string[];
  scopeSalaries: string[];
  staff: boolean;
  startSalary: string | null;
  startWork: string | null;
  status: string | null;
  taxAndInsurance: string | null;
  telegramUser: string | null;
  title: Title;
  titleCode: string;
  typeMoney: string | null;
  username: string;
  viewTaxAndInsurance: boolean;
};

export type RegistrationApiResponse = {
  code: string | null;
  count: number;
  error: boolean;
  message: string | null;
  result: Result;
  showMessage: boolean;
};
